language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
addons:
    apt:
        packages:
            libhsclient-dev
    mariadb: "10.0"
install:
    - composer self-update
    - composer require tz-lom/HSPHP:dev-master
    - wget https://github.com/kjdev/php-ext-handlersocketi/archive/master.zip
    - unzip master.zip
    - "cd php-ext-handlersocketi-master && phpize && ./configure && sudo make install"
before_script:
    - cd ..
    - sudo cp tests/travis/hs.cnf /etc/mysql/conf.d/hs.cnf
    - mysql -e 'INSTALL PLUGIN handlersocket SONAME "handlersocket.so"' -uroot
    - sudo service mysql restart
    - mysql -uroot < tests/import.sql
    - phpenv config-add tests/travis/hs.ini
